version: "3.8"
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /services/samba/shares/RPiShare:/sharepath
      - /media:/hamedia
    command: >
      -u "user;password"
      -s "RPiShare;/sharepath;yes;no"
      -s "HAMedia;/hamedia;yes;no"
      -p

networks:
  homelab-network:
    external: true
